// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b952cbe30bb17d29ebd1fbf085adba8bb4387f1a/promise-polyfill/index.d.ts
declare module 'promise-polyfill' {
// Type definitions for promise v6.0.2
// Project: https://www.npmjs.com/package/promise-polyfill
// Definitions by: Steve Jenkins <https://github.com/skysteve>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export default Promise;
}
